# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\Controller\SecurityController:
        autowire: true

    AppBundle\Controller\TaskController:
        autowire: true

    AppBundle\Controller\UserController:
        autowire: true

#            public: true
#            bind:
#                $authenticationUtils: '@security.authentication_utils'
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

